export enum ErrorsCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ORG_SAME_EMAIL_ALREADY_EXISTS = 'ORG_SAME_EMAIL_ALREADY_EXISTS',
  ORG_SAME_NAME_ALREADY_EXISTS = 'ORG_SAME_NAME_ALREADY_EXISTS',
}
